spring:
  datasource:
    url: jdbc:mysql://db4free.net:3306/saes4_database
    username: saes4_user
    password: saes4saes
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
debug: true